import React from 'react';
import {
  View,
  Text,
  StyleSheet,
  SafeAreaView,
  ScrollView,
  TouchableOpacity,
  useColorScheme,
} from 'react-native';
import { StatusBar } from 'expo-status-bar';
import { MaterialIcons } from '@expo/vector-icons';
import type { NativeStackNavigationProp } from '@react-navigation/native-stack';

type RootStackParamList = {
  About: undefined;
  Disclaimer: undefined;
};

type DisclaimerNavigationProp = NativeStackNavigationProp<RootStackParamList, 'Disclaimer'>;

interface Props {
  navigation: DisclaimerNavigationProp;
}

// Disclaimer content as constants for easy editing
const DISCLAIMER_SECTIONS = {
  GENERAL_MEDICAL: {
    title: 'General Medical Disclaimer',
    content: 'This app is intended for use by qualified healthcare professionals only. It is a decision-support tool and does not replace clinical judgment. Final diagnosis and treatment decisions must be made by a licensed healthcare provider who has evaluated the patient in person.'
  },
  RISK_CALCULATORS: {
    title: 'Risk Calculators Disclaimer',
    content: 'Risk scores (ASCVD, Framingham, Gail, Tyrer-Cuzick, Wells, FRAX, etc.) are based on published predictive models. They provide estimates only and may not reflect all clinical factors. Interpret results in the context of the full clinical evaluation.'
  },
  TREATMENT_PLAN: {
    title: 'Treatment Plan Disclaimer',
    content: 'Treatment recommendations generated by this app are suggestions based on guideline-driven algorithms. They are not prescriptions. Clinicians must verify suitability, check for contraindications, and discuss options with the patient before initiation.'
  },
  DATA_PRIVACY: {
    title: 'Data & Privacy Disclaimer',
    content: 'Patient data entered into this app is stored locally on the device unless otherwise configured. The app does not transmit data to external servers by default. Users are responsible for maintaining patient confidentiality and complying with local regulations.'
  },
  CME_EDUCATION: {
    title: 'CME / Educational Content',
    content: 'CME quizzes and educational materials are for professional learning only and are not a substitute for accredited training.'
  },
  EXPORTED_REPORT: {
    title: 'Exported Report Footer (short)',
    content: 'This report was generated by MHT Assessment for clinical decision-support. Not a substitute for clinical judgment. Confidential.'
  }
};

export default function DisclaimerScreen({ navigation }: Props) {
  const colorScheme = useColorScheme();
  const isDarkMode = colorScheme === 'dark';

  return (
    <SafeAreaView style={[styles.container, isDarkMode && styles.containerDark]}>
      <StatusBar style={isDarkMode ? "light" : "dark"} backgroundColor="#FFC1CC" />
      
      {/* Header */}
      <View style={[styles.header, isDarkMode && styles.headerDark]}>
        <TouchableOpacity
          style={[styles.backButton, isDarkMode && styles.backButtonDark]}
          onPress={() => navigation.goBack()}
          accessibilityRole="button"
          accessibilityLabel="Go back to About screen"
        >
          <MaterialIcons name="arrow-back" size={24} color={isDarkMode ? "#FFC1CC" : "#D81B60"} />
        </TouchableOpacity>
        <Text style={[styles.title, isDarkMode && styles.titleDark]} accessibilityRole="header">
          Disclaimer
        </Text>
        <View style={styles.placeholder} />
      </View>

      <ScrollView 
        style={[styles.content, isDarkMode && styles.contentDark]} 
        showsVerticalScrollIndicator={false}
        contentContainerStyle={styles.scrollContent}
      >
        {/* General Medical Disclaimer */}
        <View style={styles.section}>
          <Text 
            style={[styles.sectionTitle, isDarkMode && styles.sectionTitleDark]} 
            accessibilityRole="header"
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.GENERAL_MEDICAL.title}
          </Text>
          <Text 
            style={[styles.sectionContent, isDarkMode && styles.sectionContentDark]}
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.GENERAL_MEDICAL.content}
          </Text>
        </View>

        {/* Risk Calculators Disclaimer */}
        <View style={styles.section}>
          <Text 
            style={[styles.sectionTitle, isDarkMode && styles.sectionTitleDark]} 
            accessibilityRole="header"
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.RISK_CALCULATORS.title}
          </Text>
          <Text 
            style={[styles.sectionContent, isDarkMode && styles.sectionContentDark]}
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.RISK_CALCULATORS.content}
          </Text>
        </View>

        {/* Treatment Plan Disclaimer */}
        <View style={styles.section}>
          <Text 
            style={[styles.sectionTitle, isDarkMode && styles.sectionTitleDark]} 
            accessibilityRole="header"
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.TREATMENT_PLAN.title}
          </Text>
          <Text 
            style={[styles.sectionContent, isDarkMode && styles.sectionContentDark]}
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.TREATMENT_PLAN.content}
          </Text>
        </View>

        {/* Data & Privacy Disclaimer */}
        <View style={styles.section}>
          <Text 
            style={[styles.sectionTitle, isDarkMode && styles.sectionTitleDark]} 
            accessibilityRole="header"
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.DATA_PRIVACY.title}
          </Text>
          <Text 
            style={[styles.sectionContent, isDarkMode && styles.sectionContentDark]}
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.DATA_PRIVACY.content}
          </Text>
        </View>

        {/* CME / Educational Content */}
        <View style={styles.section}>
          <Text 
            style={[styles.sectionTitle, isDarkMode && styles.sectionTitleDark]} 
            accessibilityRole="header"
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.CME_EDUCATION.title}
          </Text>
          <Text 
            style={[styles.sectionContent, isDarkMode && styles.sectionContentDark]}
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.CME_EDUCATION.content}
          </Text>
        </View>

        {/* Exported Report Footer */}
        <View style={styles.section}>
          <Text 
            style={[styles.sectionTitle, isDarkMode && styles.sectionTitleDark]} 
            accessibilityRole="header"
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.EXPORTED_REPORT.title}
          </Text>
          <Text 
            style={[styles.sectionContent, isDarkMode && styles.sectionContentDark]}
            selectable={true}
          >
            {DISCLAIMER_SECTIONS.EXPORTED_REPORT.content}
          </Text>
        </View>

        {/* Important Note */}
        <View style={[styles.importantNote, isDarkMode && styles.importantNoteDark]}>
          <MaterialIcons 
            name="warning" 
            size={20} 
            color={isDarkMode ? "#FFB74D" : "#F57C00"} 
            style={styles.warningIcon} 
          />
          <Text 
            style={[styles.importantText, isDarkMode && styles.importantTextDark]}
            selectable={true}
          >
            This application is designed for qualified healthcare professionals only. 
            All medical decisions must be made by licensed practitioners.
          </Text>
        </View>

        <View style={styles.bottomPadding} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFF5F7',
  },
  containerDark: {
    backgroundColor: '#1A1A1A',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#FFC1CC',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  headerDark: {
    backgroundColor: '#2D1B69',
  },
  backButton: {
    padding: 12,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    minWidth: 48,
    minHeight: 48,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(216, 27, 96, 0.3)',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
  },
  backButtonDark: {
    backgroundColor: 'rgba(255, 193, 204, 0.2)',
    borderColor: 'rgba(255, 193, 204, 0.5)',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#D81B60',
    flex: 1,
    textAlign: 'center',
  },
  titleDark: {
    color: '#FFC1CC',
  },
  placeholder: {
    width: 40,
  },
  content: {
    flex: 1,
  },
  contentDark: {
    backgroundColor: '#1A1A1A',
  },
  scrollContent: {
    paddingHorizontal: 20,
  },
  section: {
    marginVertical: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#D81B60',
    marginBottom: 12,
    lineHeight: 24,
  },
  sectionTitleDark: {
    color: '#FFC1CC',
  },
  sectionContent: {
    fontSize: 16,
    color: '#333',
    lineHeight: 24,
    textAlign: 'justify',
  },
  sectionContentDark: {
    color: '#E0E0E0',
  },
  importantNote: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#FFF8E1',
    borderLeftWidth: 4,
    borderLeftColor: '#F57C00',
    padding: 16,
    marginVertical: 20,
    borderRadius: 8,
    marginHorizontal: 4,
  },
  importantNoteDark: {
    backgroundColor: '#2E2E2E',
    borderLeftColor: '#FFB74D',
  },
  warningIcon: {
    marginRight: 12,
    marginTop: 2,
  },
  importantText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '500',
    color: '#E65100',
    lineHeight: 20,
  },
  importantTextDark: {
    color: '#FFD54F',
  },
  bottomPadding: {
    height: 40,
  },
});

export { DISCLAIMER_SECTIONS };