name: Build Android APK

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release)'
        required: false
        default: 'debug'
        type: choice
        options:
        - debug
        - release

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    env:
      JAVA_VERSION: '17'
      NODE_VERSION: '20'
      
    steps:
    - name: 📚 Checkout repository
      uses: actions/checkout@v4
      
    - name: ☕ Setup Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        
    - name: 📱 Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 34
        build-tools-version: 34.0.0
        
    - name: 🏗️ Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        
    - name: 📦 Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: 🧹 Clean build artifacts
      run: |
        rm -rf android/app/src/main/assets/index.android.bundle
        rm -rf android/app/src/main/res/drawable-*
        rm -rf android/app/src/main/res/raw
        cd android && ./gradlew clean && cd ..
        
    - name: 📁 Create assets directory
      run: |
        mkdir -p android/app/src/main/assets
        mkdir -p android/app/src/main/res
        
    - name: ⚡ Bundle JavaScript for Android
      run: |
        npx react-native bundle \
          --platform android \
          --dev false \
          --entry-file index.js \
          --bundle-output android/app/src/main/assets/index.android.bundle \
          --assets-dest android/app/src/main/res/ \
          --reset-cache
          
    - name: 📊 Verify bundle creation
      run: |
        if [ ! -f "android/app/src/main/assets/index.android.bundle" ]; then
          echo "❌ Bundle file not found!"
          exit 1
        fi
        echo "✅ Bundle size: $(ls -lh android/app/src/main/assets/index.android.bundle | awk '{print $5}')"
        
    - name: 🔨 Build Debug APK
      if: github.event_name != 'workflow_dispatch' || github.event.inputs.build_type == 'debug'
      run: |
        cd android
        ./gradlew assembleDebug --stacktrace
        cd ..
        
    - name: 🔨 Build Release APK
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.build_type == 'release'
      run: |
        cd android
        ./gradlew assembleRelease --stacktrace
        cd ..
        
    - name: 📱 Locate APK files
      id: locate_apk
      run: |
        if [ "${{ github.event.inputs.build_type }}" == "release" ] || [ "${{ github.event_name }}" == "push" ] && [[ "${{ github.ref }}" == refs/tags/* ]]; then
          BUILD_TYPE="release"
        else
          BUILD_TYPE="debug"
        fi
        
        APK_PATH=$(find android/app/build/outputs/apk/$BUILD_TYPE -name "*.apk" | head -1)
        
        if [ -z "$APK_PATH" ]; then
          echo "❌ APK not found!"
          exit 1
        fi
        
        APK_NAME="mht-assessment-standalone-$BUILD_TYPE.apk"
        cp "$APK_PATH" "$APK_NAME"
        
        echo "apk_path=$APK_NAME" >> $GITHUB_OUTPUT
        echo "apk_size=$(ls -lh $APK_NAME | awk '{print $5}')" >> $GITHUB_OUTPUT
        echo "build_type=$BUILD_TYPE" >> $GITHUB_OUTPUT
        
    - name: 📤 Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: mht-assessment-apk-${{ steps.locate_apk.outputs.build_type }}
        path: ${{ steps.locate_apk.outputs.apk_path }}
        retention-days: 30
        
    - name: 📋 Build Summary
      run: |
        echo "## 🎉 Android APK Build Complete!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Build Details:**" >> $GITHUB_STEP_SUMMARY
        echo "- **APK Name:** ${{ steps.locate_apk.outputs.apk_path }}" >> $GITHUB_STEP_SUMMARY
        echo "- **APK Size:** ${{ steps.locate_apk.outputs.apk_size }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Type:** ${{ steps.locate_apk.outputs.build_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Java Version:** ${{ env.JAVA_VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Node Version:** ${{ env.NODE_VERSION }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Installation Instructions:**" >> $GITHUB_STEP_SUMMARY
        echo "1. Download the APK from the artifacts section above" >> $GITHUB_STEP_SUMMARY
        echo "2. Enable 'Unknown Sources' on your Android device" >> $GITHUB_STEP_SUMMARY
        echo "3. Install via USB debugging: \`adb install ${{ steps.locate_apk.outputs.apk_path }}\`" >> $GITHUB_STEP_SUMMARY
        echo "4. Or transfer to device and install via file manager" >> $GITHUB_STEP_SUMMARY
        
    - name: 🏷️ Create Release (on tag push)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ steps.locate_apk.outputs.apk_path }}
        draft: false
        prerelease: false
        body: |
          ## MHT Assessment - Standalone Android APK
          
          **Build Information:**
          - APK Size: ${{ steps.locate_apk.outputs.apk_size }}
          - Build Type: ${{ steps.locate_apk.outputs.build_type }}
          - Target SDK: Android 14 (API 34)
          - Minimum SDK: Android 6.0 (API 23)
          
          **Installation:**
          1. Download the APK file below
          2. Enable "Unknown Sources" in Android settings
          3. Install the APK on your device
          
          **Features:**
          - Self-contained (no Metro server required)
          - Universal APK (works on all Android architectures)
          - Offline patient data storage
          - Complete CME quiz functionality
          - Risk calculators and assessment tools
          
          **Verification:**
          - ✅ APK is self-contained and doesn't require Metro
          - ✅ All app features work offline
          - ✅ Universal compatibility across Android devices
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}